---
baseurl: "/"
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
permalink: /404.html
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
 - jekyll-paginate
 - jekyll-seo-tag
exclude:
 - nbproject
plugins:
 - jekyll-seo-tag
title: "Documentation plugin Somfy Home Alarm"
description: "Ceci est la documentation, liée au plugin Somfy Home Alarm pour Jeedom."
author: "erobert-c"
image: https://www.jeedom.com/site/logo.png